apiVersion: v1
entries:
  bookinfo:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.032902+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 7972d3cc44e21e43212ec080f9b01f77db02575ce1bff6cd4ee5e58e5f801481
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.1.3.tgz
    version: 2.1.3
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.031239+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 37348274c992ec5719f6d6bc75a31e75731b183e00c841b3d97461579546bb3d
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.1.2.tgz
    version: 2.1.2
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.029375+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 91fa5994af089bed596d215ab2ee6eacc5549719c7ca1cc177d2676c40c9b556
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.027151+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 73463856037ff085a0deac4675f641355432c21d5d9511bfc414f77bf3bf541d
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.0.3.tgz
    version: 2.0.3
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.024993+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: c85638dcb652c52449971052a0b32b80a9e4ae845acef3ee96a37dbd6daa8822
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.021785+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 588ca452766bf279e0b36fd829916a62b2196e02795d4c4e73b23c2d33c0dd9b
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.019417+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 22b642a8c96631f0ecdb72125aabc2722f45eb3078132885340ca17f3cbe7ac3
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:33.997269+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 94d920697816f44ed26b7d7aad346046db862eac6bde8daf8ce9f2a72dd1709b
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.10.tgz
    version: 1.0.10
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.016963+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 0e60d04e7fb2417783056b6f73577e1483aa333d2fc46e7e13863e73ed68e5db
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.015009+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 834f686049652e545e14838d42bc35da21d7eba107307cfeaf0148f848a6ca7b
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.011709+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 62cf2c73737db9016570a3c7069707dff256efdb3a6cb9e65afc51708576ad1b
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.009633+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 64348f800a33298c440f8195e01202dfe824ed8df82944fc242a06fe0f5885b2
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.007479+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 0e78cb0c40875dfbe548652cf472a73af28e2495fc40206d6a5fa49bf17e0c0c
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.004221+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 9dcc362f03b4367da92969550bb9dcc4d7161e232ee954394c2f2a88a10d4351
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.001251+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 37c9c3d3b4c5e39c76227cd205ee6b1550e84290a9dcae963c8f75cf79092e31
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:33.999159+08:00"
    description: A Helm chart for bookinfo app (based on sample Istio app)
    digest: 985da123a8fcc1e524cfc663781f05206b24e75335b92965eb8edbfc63927f50
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:33.994852+08:00"
    description: A Helm chart for bookinfo app (Sample Istio app)
    digest: 0de3041c1f28aa462cfa56455d2808fde1f9fb24417f14158c6d412601f35dea
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:33.992799+08:00"
    description: A Helm chart for bookinfo app (Sample Istio app)
    digest: 8dd722ce248107aa614a11e0ace51db139b131a88083bd4ba5a6a3545461ba8a
    icon: https://ibm-icp-coc.github.io/charts/repo/stable/bookinfo.png
    keywords:
    - sample
    - istio
    - bookinfo
    - ruby
    - python
    - liberty
    - mysql
    - ICAM
    - CloudPak
    name: bookinfo
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/bookinfo-1.0.0.tgz
    version: 1.0.0
  checkout:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-15T19:43:34.033638+08:00"
    description: A Helm chart for Kubernetes
    digest: 92f18276a34a228ed67c7e8c86c106a7af22c6f9f1429311e2a46e459fae910a
    name: checkout
    urls:
    - https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/checkout-0.1.0.tgz
    version: 0.1.0
generated: "2020-04-15T19:43:33.986573+08:00"
